version: 2.1
jobs:
  tests:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
      - image: dgraph/standalone:v21.03.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go mod download
            go get golang.org/x/tools/cmd/cover
            go get github.com/mattn/goveralls
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            go test -v -covermode=count -coverprofile=coverage.out
            goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN

workflows:
  tests:
    jobs:
      - tests